# p34.py
# Layla Gallez
# 3/21/2021
# Python 3.8.1
# Description: Program to show output in Python

def recursive(input1):

    if input1 == 0:
        print("No more cans of White Claw on the wall, no more cans of White Claw. Go to the store and buy some more, 99 cans of White Claw on the wall.")
    if input1 == 1:
        print('1 cans of White Claw on the wall, 1 cans of White Claw. Take one down and pass it around, no more cans of White Claw on the wall. \n'
              'No more cans of White Claw on the wall, no more cans of White Claw. Go to the store and buy some more, 99 cans of White Claw on the wall. ')
    else:
        print(input1, ' cans of White Claw on the wall, ', input1, 'cans of White Claw. Take one down, pass it around, ', (input1-1), 'cans of White Claw on the wall...')
        recursive(input1-1)

recursive(99)


'''
/Users/layla.gallez/Desktop/laylaStuff/school/gavilan/python/venv/bin/python /Users/layla.gallez/Desktop/laylaStuff/school/gavilan/python/main.py
99  cans of White Claw on the wall,  99 cans of White Claw. Take one down, pass it around,  98 cans of White Claw on the wall...
98  cans of White Claw on the wall,  98 cans of White Claw. Take one down, pass it around,  97 cans of White Claw on the wall...
97  cans of White Claw on the wall,  97 cans of White Claw. Take one down, pass it around,  96 cans of White Claw on the wall...
96  cans of White Claw on the wall,  96 cans of White Claw. Take one down, pass it around,  95 cans of White Claw on the wall...
95  cans of White Claw on the wall,  95 cans of White Claw. Take one down, pass it around,  94 cans of White Claw on the wall...
94  cans of White Claw on the wall,  94 cans of White Claw. Take one down, pass it around,  93 cans of White Claw on the wall...
93  cans of White Claw on the wall,  93 cans of White Claw. Take one down, pass it around,  92 cans of White Claw on the wall...
92  cans of White Claw on the wall,  92 cans of White Claw. Take one down, pass it around,  91 cans of White Claw on the wall...
91  cans of White Claw on the wall,  91 cans of White Claw. Take one down, pass it around,  90 cans of White Claw on the wall...
90  cans of White Claw on the wall,  90 cans of White Claw. Take one down, pass it around,  89 cans of White Claw on the wall...
89  cans of White Claw on the wall,  89 cans of White Claw. Take one down, pass it around,  88 cans of White Claw on the wall...
88  cans of White Claw on the wall,  88 cans of White Claw. Take one down, pass it around,  87 cans of White Claw on the wall...
87  cans of White Claw on the wall,  87 cans of White Claw. Take one down, pass it around,  86 cans of White Claw on the wall...
86  cans of White Claw on the wall,  86 cans of White Claw. Take one down, pass it around,  85 cans of White Claw on the wall...
85  cans of White Claw on the wall,  85 cans of White Claw. Take one down, pass it around,  84 cans of White Claw on the wall...
84  cans of White Claw on the wall,  84 cans of White Claw. Take one down, pass it around,  83 cans of White Claw on the wall...
83  cans of White Claw on the wall,  83 cans of White Claw. Take one down, pass it around,  82 cans of White Claw on the wall...
82  cans of White Claw on the wall,  82 cans of White Claw. Take one down, pass it around,  81 cans of White Claw on the wall...
81  cans of White Claw on the wall,  81 cans of White Claw. Take one down, pass it around,  80 cans of White Claw on the wall...
80  cans of White Claw on the wall,  80 cans of White Claw. Take one down, pass it around,  79 cans of White Claw on the wall...
79  cans of White Claw on the wall,  79 cans of White Claw. Take one down, pass it around,  78 cans of White Claw on the wall...
78  cans of White Claw on the wall,  78 cans of White Claw. Take one down, pass it around,  77 cans of White Claw on the wall...
77  cans of White Claw on the wall,  77 cans of White Claw. Take one down, pass it around,  76 cans of White Claw on the wall...
76  cans of White Claw on the wall,  76 cans of White Claw. Take one down, pass it around,  75 cans of White Claw on the wall...
75  cans of White Claw on the wall,  75 cans of White Claw. Take one down, pass it around,  74 cans of White Claw on the wall...
74  cans of White Claw on the wall,  74 cans of White Claw. Take one down, pass it around,  73 cans of White Claw on the wall...
73  cans of White Claw on the wall,  73 cans of White Claw. Take one down, pass it around,  72 cans of White Claw on the wall...
72  cans of White Claw on the wall,  72 cans of White Claw. Take one down, pass it around,  71 cans of White Claw on the wall...
71  cans of White Claw on the wall,  71 cans of White Claw. Take one down, pass it around,  70 cans of White Claw on the wall...
70  cans of White Claw on the wall,  70 cans of White Claw. Take one down, pass it around,  69 cans of White Claw on the wall...
69  cans of White Claw on the wall,  69 cans of White Claw. Take one down, pass it around,  68 cans of White Claw on the wall...
68  cans of White Claw on the wall,  68 cans of White Claw. Take one down, pass it around,  67 cans of White Claw on the wall...
67  cans of White Claw on the wall,  67 cans of White Claw. Take one down, pass it around,  66 cans of White Claw on the wall...
66  cans of White Claw on the wall,  66 cans of White Claw. Take one down, pass it around,  65 cans of White Claw on the wall...
65  cans of White Claw on the wall,  65 cans of White Claw. Take one down, pass it around,  64 cans of White Claw on the wall...
64  cans of White Claw on the wall,  64 cans of White Claw. Take one down, pass it around,  63 cans of White Claw on the wall...
63  cans of White Claw on the wall,  63 cans of White Claw. Take one down, pass it around,  62 cans of White Claw on the wall...
62  cans of White Claw on the wall,  62 cans of White Claw. Take one down, pass it around,  61 cans of White Claw on the wall...
61  cans of White Claw on the wall,  61 cans of White Claw. Take one down, pass it around,  60 cans of White Claw on the wall...
60  cans of White Claw on the wall,  60 cans of White Claw. Take one down, pass it around,  59 cans of White Claw on the wall...
59  cans of White Claw on the wall,  59 cans of White Claw. Take one down, pass it around,  58 cans of White Claw on the wall...
58  cans of White Claw on the wall,  58 cans of White Claw. Take one down, pass it around,  57 cans of White Claw on the wall...
57  cans of White Claw on the wall,  57 cans of White Claw. Take one down, pass it around,  56 cans of White Claw on the wall...
56  cans of White Claw on the wall,  56 cans of White Claw. Take one down, pass it around,  55 cans of White Claw on the wall...
55  cans of White Claw on the wall,  55 cans of White Claw. Take one down, pass it around,  54 cans of White Claw on the wall...
54  cans of White Claw on the wall,  54 cans of White Claw. Take one down, pass it around,  53 cans of White Claw on the wall...
53  cans of White Claw on the wall,  53 cans of White Claw. Take one down, pass it around,  52 cans of White Claw on the wall...
52  cans of White Claw on the wall,  52 cans of White Claw. Take one down, pass it around,  51 cans of White Claw on the wall...
51  cans of White Claw on the wall,  51 cans of White Claw. Take one down, pass it around,  50 cans of White Claw on the wall...
50  cans of White Claw on the wall,  50 cans of White Claw. Take one down, pass it around,  49 cans of White Claw on the wall...
49  cans of White Claw on the wall,  49 cans of White Claw. Take one down, pass it around,  48 cans of White Claw on the wall...
48  cans of White Claw on the wall,  48 cans of White Claw. Take one down, pass it around,  47 cans of White Claw on the wall...
47  cans of White Claw on the wall,  47 cans of White Claw. Take one down, pass it around,  46 cans of White Claw on the wall...
46  cans of White Claw on the wall,  46 cans of White Claw. Take one down, pass it around,  45 cans of White Claw on the wall...
45  cans of White Claw on the wall,  45 cans of White Claw. Take one down, pass it around,  44 cans of White Claw on the wall...
44  cans of White Claw on the wall,  44 cans of White Claw. Take one down, pass it around,  43 cans of White Claw on the wall...
43  cans of White Claw on the wall,  43 cans of White Claw. Take one down, pass it around,  42 cans of White Claw on the wall...
42  cans of White Claw on the wall,  42 cans of White Claw. Take one down, pass it around,  41 cans of White Claw on the wall...
41  cans of White Claw on the wall,  41 cans of White Claw. Take one down, pass it around,  40 cans of White Claw on the wall...
40  cans of White Claw on the wall,  40 cans of White Claw. Take one down, pass it around,  39 cans of White Claw on the wall...
39  cans of White Claw on the wall,  39 cans of White Claw. Take one down, pass it around,  38 cans of White Claw on the wall...
38  cans of White Claw on the wall,  38 cans of White Claw. Take one down, pass it around,  37 cans of White Claw on the wall...
37  cans of White Claw on the wall,  37 cans of White Claw. Take one down, pass it around,  36 cans of White Claw on the wall...
36  cans of White Claw on the wall,  36 cans of White Claw. Take one down, pass it around,  35 cans of White Claw on the wall...
35  cans of White Claw on the wall,  35 cans of White Claw. Take one down, pass it around,  34 cans of White Claw on the wall...
34  cans of White Claw on the wall,  34 cans of White Claw. Take one down, pass it around,  33 cans of White Claw on the wall...
33  cans of White Claw on the wall,  33 cans of White Claw. Take one down, pass it around,  32 cans of White Claw on the wall...
32  cans of White Claw on the wall,  32 cans of White Claw. Take one down, pass it around,  31 cans of White Claw on the wall...
31  cans of White Claw on the wall,  31 cans of White Claw. Take one down, pass it around,  30 cans of White Claw on the wall...
30  cans of White Claw on the wall,  30 cans of White Claw. Take one down, pass it around,  29 cans of White Claw on the wall...
29  cans of White Claw on the wall,  29 cans of White Claw. Take one down, pass it around,  28 cans of White Claw on the wall...
28  cans of White Claw on the wall,  28 cans of White Claw. Take one down, pass it around,  27 cans of White Claw on the wall...
27  cans of White Claw on the wall,  27 cans of White Claw. Take one down, pass it around,  26 cans of White Claw on the wall...
26  cans of White Claw on the wall,  26 cans of White Claw. Take one down, pass it around,  25 cans of White Claw on the wall...
25  cans of White Claw on the wall,  25 cans of White Claw. Take one down, pass it around,  24 cans of White Claw on the wall...
24  cans of White Claw on the wall,  24 cans of White Claw. Take one down, pass it around,  23 cans of White Claw on the wall...
23  cans of White Claw on the wall,  23 cans of White Claw. Take one down, pass it around,  22 cans of White Claw on the wall...
22  cans of White Claw on the wall,  22 cans of White Claw. Take one down, pass it around,  21 cans of White Claw on the wall...
21  cans of White Claw on the wall,  21 cans of White Claw. Take one down, pass it around,  20 cans of White Claw on the wall...
20  cans of White Claw on the wall,  20 cans of White Claw. Take one down, pass it around,  19 cans of White Claw on the wall...
19  cans of White Claw on the wall,  19 cans of White Claw. Take one down, pass it around,  18 cans of White Claw on the wall...
18  cans of White Claw on the wall,  18 cans of White Claw. Take one down, pass it around,  17 cans of White Claw on the wall...
17  cans of White Claw on the wall,  17 cans of White Claw. Take one down, pass it around,  16 cans of White Claw on the wall...
16  cans of White Claw on the wall,  16 cans of White Claw. Take one down, pass it around,  15 cans of White Claw on the wall...
15  cans of White Claw on the wall,  15 cans of White Claw. Take one down, pass it around,  14 cans of White Claw on the wall...
14  cans of White Claw on the wall,  14 cans of White Claw. Take one down, pass it around,  13 cans of White Claw on the wall...
13  cans of White Claw on the wall,  13 cans of White Claw. Take one down, pass it around,  12 cans of White Claw on the wall...
12  cans of White Claw on the wall,  12 cans of White Claw. Take one down, pass it around,  11 cans of White Claw on the wall...
11  cans of White Claw on the wall,  11 cans of White Claw. Take one down, pass it around,  10 cans of White Claw on the wall...
10  cans of White Claw on the wall,  10 cans of White Claw. Take one down, pass it around,  9 cans of White Claw on the wall...
9  cans of White Claw on the wall,  9 cans of White Claw. Take one down, pass it around,  8 cans of White Claw on the wall...
8  cans of White Claw on the wall,  8 cans of White Claw. Take one down, pass it around,  7 cans of White Claw on the wall...
7  cans of White Claw on the wall,  7 cans of White Claw. Take one down, pass it around,  6 cans of White Claw on the wall...
6  cans of White Claw on the wall,  6 cans of White Claw. Take one down, pass it around,  5 cans of White Claw on the wall...
5  cans of White Claw on the wall,  5 cans of White Claw. Take one down, pass it around,  4 cans of White Claw on the wall...
4  cans of White Claw on the wall,  4 cans of White Claw. Take one down, pass it around,  3 cans of White Claw on the wall...
3  cans of White Claw on the wall,  3 cans of White Claw. Take one down, pass it around,  2 cans of White Claw on the wall...
2  cans of White Claw on the wall,  2 cans of White Claw. Take one down, pass it around,  1 cans of White Claw on the wall...
1 cans of White Claw on the wall, 1 cans of White Claw. Take one down and pass it around, no more cans of White Claw on the wall. 
No more cans of White Claw on the wall, no more cans of White Claw. Go to the store and buy some more, 99 cans of White Claw on the wall. 

Process finished with exit code 0
'''